apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
    type: frontend
spec:
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
        type: frontend
    spec:
      containers:
      - name: frontend
        image: nginx
  selector:
    matchLabels:
      type: frontend
  replicas: 2