apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
    type: redis
spec:
  template:
    metadata:
      name: redis
      labels:
        app: redis
        type: redis
    spec:
      containers:
      - name: redis
        image: redis
  selector:
    matchLabels:
      type: redis
  replicas: 2