apiVersion: v1
kind: Pod
metadata: 
    name: webserver
    labels: 
      name: webserver
spec:
    containers:
    - name: webserver
      image: adanbueno/webserver
      ports:
        - containerPort: 8080